<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class BackupDatabase extends Command
{
    protected $signature = 'app:backup-database';
    protected $description = 'Creates a full SQL backup of the database using PDO';

    public function handle(): int
    {
        $backupDir = storage_path('app/backups');

        // Ensure backup directory exists
        if (!is_dir($backupDir)) {
            mkdir($backupDir, 0755, true);
            $this->info("Created backup directory: {$backupDir}");
        }

        $filename = 'backup_' . now()->format('Y-m-d_H-i-s') . '.sql';
        $filepath = $backupDir . DIRECTORY_SEPARATOR . $filename;

        try {
            $host     = config('database.connections.mysql.host', '127.0.0.1');
            $port     = config('database.connections.mysql.port', '3306');
            $dbname   = config('database.connections.mysql.database');
            $username = config('database.connections.mysql.username');
            $password = config('database.connections.mysql.password');
            $charset  = config('database.connections.mysql.charset', 'utf8mb4');

            $dsn = "mysql:host={$host};port={$port};dbname={$dbname};charset={$charset}";
            $pdo = new \PDO($dsn, $username, $password, [
                \PDO::ATTR_ERRMODE            => \PDO::ERRMODE_EXCEPTION,
                \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
            ]);

            $output  = "-- GovSaúde Database Backup\n";
            $output .= "-- Database: {$dbname}\n";
            $output .= "-- Date: " . now()->toDateTimeString() . "\n";
            $output .= "-- Generated by BackupDatabase Artisan command\n\n";
            $output .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

            // Get all tables
            $tables = $pdo->query('SHOW TABLES')->fetchAll(\PDO::FETCH_COLUMN);
            $this->info('Found ' . count($tables) . ' tables to backup.');

            foreach ($tables as $table) {
                $this->line("  Backing up table: {$table}");

                // CREATE TABLE statement
                $createRow = $pdo->query("SHOW CREATE TABLE `{$table}`")->fetch();
                $createSql = array_values($createRow)[1];
                $output .= "-- --------------------------------------------------------\n";
                $output .= "-- Table structure for `{$table}`\n";
                $output .= "-- --------------------------------------------------------\n\n";
                $output .= "DROP TABLE IF EXISTS `{$table}`;\n";
                $output .= $createSql . ";\n\n";

                // Get all rows
                $rowStmt  = $pdo->query("SELECT * FROM `{$table}`");
                $rows     = $rowStmt->fetchAll();

                if (empty($rows)) {
                    $output .= "-- No data in table `{$table}`\n\n";
                    continue;
                }

                $columns = array_keys($rows[0]);
                $colList = implode(', ', array_map(fn($c) => "`{$c}`", $columns));

                $output .= "-- Data for table `{$table}`\n\n";

                // Process in chunks of 500
                $chunks = array_chunk($rows, 500);
                foreach ($chunks as $chunk) {
                    $output .= "INSERT INTO `{$table}` ({$colList}) VALUES\n";
                    $valueLines = [];
                    foreach ($chunk as $row) {
                        $values = array_map(function ($val) use ($pdo) {
                            if ($val === null) return 'NULL';
                            return $pdo->quote((string) $val);
                        }, array_values($row));
                        $valueLines[] = '(' . implode(', ', $values) . ')';
                    }
                    $output .= implode(",\n", $valueLines) . ";\n";
                }
                $output .= "\n";
            }

            $output .= "SET FOREIGN_KEY_CHECKS=1;\n";
            $output .= "-- Backup complete\n";

            file_put_contents($filepath, $output);
            $this->info("Backup saved: {$filename}");

            // Keep only the last 30 backups
            $allFiles = glob($backupDir . DIRECTORY_SEPARATOR . '*.sql') ?: [];
            usort($allFiles, fn($a, $b) => filemtime($b) - filemtime($a));

            if (count($allFiles) > 30) {
                $toDelete = array_slice($allFiles, 30);
                foreach ($toDelete as $old) {
                    unlink($old);
                    $this->line('  Deleted old backup: ' . basename($old));
                }
            }

            $this->info('Backup completed successfully.');
            return self::SUCCESS;

        } catch (\Exception $e) {
            $this->error('Backup failed: ' . $e->getMessage());
            // Clean up partial file if it exists
            if (file_exists($filepath)) {
                unlink($filepath);
            }
            return self::FAILURE;
        }
    }
}
